
##??????????????true
#spring.servlet.multipart.enabled=true
##?????????????0
#spring.servlet.multipart.file-size-threshold=0

##????????????50MB
#spring.servlet.multipart.max-file-size=50MB
##??????????? ?????100MB
#spring.servlet.multipart.max-request-size=100MB
##??????????false
#spring.servlet.multipart.resolve-lazily=false
server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/_project?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 100MB
    # mail邮箱
  mail:
    # SMTP服务器（我用的是QQ邮箱的SMTP服务器地址，如果用的其它邮箱请另行百度搜索）
    host: smtp.qq.com
    # 发送验证码的邮箱（发件人的邮箱）
    username: 1991016977@qq.com
    # 授权码
    password: effgbzpufqqzfbgg
    # 编码
    default-encoding: utf-8
    # 其它参数
    properties:
      mail:
        smtp:
          # 如果是用SSL方式，需要配置如下属性,使用qq邮箱的话需要开启
          ssl:
            enable: true
            required: true
          # 邮件接收时间的限制，单位毫秒
          timeout: 10000
          # 连接时间的限制，单位毫秒
          connection-timeout: 10000
          # 邮件发送时间的限制，单位毫秒
          write-timeout: 10000
ip: localhost
