
##??????????????true
#spring.servlet.multipart.enabled=true
##?????????????0
#spring.servlet.multipart.file-size-threshold=0

##????????????50MB
#spring.servlet.multipart.max-file-size=50MB
##??????????? ?????100MB
#spring.servlet.multipart.max-request-size=100MB
##??????????false
#spring.servlet.multipart.resolve-lazily=false
server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/_project?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 100MB
ip: localhost
